[package]
name = "derive_vertex_attribute"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
inflections = "1.1.1"
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = { version = "1.0.81", features = ["full"] }
