[package]
name = "limelight-example-instances"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.74"
web-sys = "0.3.51"
limelight = { path="../../limelight" }
bytemuck = { version = "1.7.2", features = ["derive"] }
