name: Deploy Demos

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build demos
      run: |
        mkdir dist
        cd examples
        for DEMO_DIR in $(ls -d */)
        do
          cd "${DEMO_DIR}"
          ~/trunk build --public-url="/limelight/${DEMO_DIR}/"
          mv dist "../../dist/${DEMO_DIR}"
          cd ../
        done
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: dist
